version: "3"

services:
  php:
    build: ./docker/php
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: app-mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33061:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    privileged: true
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
